kind: Service
apiVersion: v1
metadata:
  name: backend
spec:
  selector:
    app: bee-bee-alert
    tier: backend
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 9090

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: bee-bee-alert
        tier: backend
    spec:
      containers:
      - name: backend
        image: "gcr.io/bee-bee-alert-jimlin/backend:0.0.6"
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: config-volume
          mountPath: /go/src/github.com/Jim-Lin/bee-bee-alert/backend

      volumes:
      - name: config-volume
        configMap:
          name: backend-config
