kind: Service
apiVersion: v1
metadata:
  name: elasticsearch
spec:
  selector:
    app: bee-bee-alert
    tier: elasticsearch
  ports:
  - name: http
    port: 9200
    protocol: TCP
  - name: transport
    port: 9300
    protocol: TCP

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: elasticsearch
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: bee-bee-alert
        tier: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: "gcr.io/bee-bee-alert-jimlin/elasticsearch:6.0.0"
        ports:
        - containerPort: 9200
          name: http
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: esdata
      volumes:
      - name: esdata
        emptyDir: {}
