apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: bee-bee-alert
    tier: nginx
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: LoadBalancer

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: bee-bee-alert
        tier: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config-volume
          subPath: default.conf
          mountPath: /etc/nginx/conf.d/default.conf

      volumes:
      - name: config-volume
        configMap:
          name: nginx-config
